# https://github.com/purcell/nix-emacs-ci
language: nix

cache:
  directories:
  - $HOME/nix.store

sudo: false

jobs:
  include:
    - os: linux
      dist: bionic
      env: EMACS_CI=emacs-24-3
    - os: linux
      dist: bionic
      env: EMACS_CI=emacs-24-4
    - os: linux
      dist: bionic
      env: EMACS_CI=emacs-24-5
    - os: linux
      dist: bionic
      env: EMACS_CI=emacs-25-1
    - os: linux
      dist: bionic
      env: EMACS_CI=emacs-25-2
    - os: linux
      dist: bionic
      env: EMACS_CI=emacs-25-3
    - os: linux
      dist: bionic
      env: EMACS_CI=emacs-26-1
    - os: linux
      dist: bionic
      env: EMACS_CI=emacs-26-2
    - os: linux
      dist: bionic
      env: EMACS_CI=emacs-26-3
    - os: linux
      dist: bionic
      env: EMACS_CI=emacs-27-1
    - os: linux
      dist: bionic
      env: EMACS_CI=emacs-snapshot


before_install:
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

before_cache:
  - mkdir -p $HOME/nix.store
  - nix copy --to file://$HOME/nix.store -f default.nix buildInputs

install:
  # The default "emacs" executable on the $PATH will now be the version named by $EMACS_CI
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
  - emacs --version
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
  - cask
  - make start-server

script:
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
  - make test

after_failure:
  - cat test/servant/tmp/servant.log

after_script:
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
  - make stop-server

allow_failures:
  - os: linux
    dist: bionic
    env: EMACS_CI=emacs-snapshot
