# https://github.com/purcell/nix-emacs-ci
# https://nixos.wiki/wiki/Nix_on_Travis
language: nix

cache:
  directories:
  - $HOME/nix.store

sudo: false

os: linux
dist: bionic

env:
  - EMACS_CI=emacs-24-3 FOO=bar
  - EMACS_CI=emacs-24-4 FOO=bar
  - EMACS_CI=emacs-24-5 FOO=bar
  - EMACS_CI=emacs-25-1 FOO=bar
  - EMACS_CI=emacs-25-2 FOO=bar
  - EMACS_CI=emacs-25-3 FOO=bar
  - EMACS_CI=emacs-26-1 FOO=bar
  - EMACS_CI=emacs-26-2 FOO=bar
  - EMACS_CI=emacs-26-3 FOO=bar
  - EMACS_CI=emacs-27-1 FOO=bar
  - EMACS_CI=emacs-snapshot FOO=bar

before_install:
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

before_cache:
  - mkdir -p $HOME/nix.store
  - nix copy --to file://$HOME/nix.store -f default.nix buildInputs

before_script:
  - sudo mkdir -p /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf

install:
  # The default "emacs" executable on the $PATH will now be the version named by $EMACS_CI
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
  - emacs --version
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
  - cask install
  - cask upgrade
  - make start-server

script:
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
  - cask --version
  - emacs --version
  # - make clean
  - make test

after_failure:
  - cat test/servant/tmp/servant.log

after_script:
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
  - make stop-server

allow_failures:
  - os: linux
    dist: bionic
    env: EMACS_CI=emacs-snapshot
